Controllers/SystemController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_crud.Models.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using MVC_crud.Data;


namespace MVC_crud.Controllers
{
    public class SystemController : Controller
    {
        private readonly MVCDBContext mvcDBContext;
        public SystemController(MVCDBContext mvcDBContext)
        {
            this.mvcDBContext = mvcDBContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> systemView()
        {
            // 從 Session 中獲取帳號名稱
            int? accountID = HttpContext.Session.GetInt32("accountID");

            var sql = @"SELECT b.Bill_ID,bd.Bill_Name,bm.Total_Amount,bm.Average_Amount,bp.Total_Users 
                        FROM Bill b
                            INNER JOIN Bill_Detail bd ON b.Bill_ID = bd.Bill_ID
                            LEFT JOIN (
                                        SELECT Bill_ID,SUM(Money) AS Total_Amount,AVG(Money) AS Average_Amount
                                                FROM Bill
                                                    GROUP BY Bill_ID
                                       ) AS bm ON b.Bill_ID = bm.Bill_ID
                            LEFT JOIN (
                                        SELECT Bill_ID,COUNT(Account_ID) AS Total_Users 
                                                FROM Bill
                                                    GROUP BY Bill_ID
                                      ) AS bp ON b.Bill_ID = bp.Bill_ID
                        WHERE b.Account_ID = @user;

";

            // 執行 SQL 查詢，並傳入使用者輸入的 CustomerID 參數
            List<BillTable>? BillTable = await mvcDBContext.BillTables
                .FromSqlRaw(sql, new SqlParameter("@user", accountID))
                .ToListAsync();

            // 這裡可以將 customerDetails 傳遞給 View 或者進行其他處理
            if (BillTable != null)
            {
                return View(model: BillTable);
            }
            else
            {
                return View();
            }

        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_crud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_crud.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_crud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enter" asp-action="login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enter" asp-action="register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="System" asp-action="systemView">SHare_System</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShareAct" asp-action="create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC_crud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>